spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/hibernate_test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: tjlee
    password: tjlee
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    open-in-view: false
    properties:
      hibernate:
        cache.use_second_level_cache: false
        default_batch_fetch_size: 20
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy