#spring:
#  datasource:
#    url: jdbc:mysql://221.148.176.245:13306/OSSTEMMEMBERS?useUnicode=true&characterEncoding=utf-8
#    username: members
#    password: osTB%u0nu
#    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database: MYSQL
#    open-in-view: false
#    properties:
#      hibernate:
#        cache.use_second_level_cache: false
#        default_batch_fetch_size: 20
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy